language: python
dist: trusty
sudo: required
python:
  - 3.5
before_install:
  - sudo apt-get -y install python3 python3-pip python3-coverage
  - python3 -V
  - pip3 -V
install:
  - sudo pip3 install -r requirements.txt
  - sudo pip3 install coveralls
script:
  python3 -m nose --with-coverage --cover-erase --cover-html --cover-package=analyzer
after_success:
  coveralls