version: '3'
services:
  beanstalksvc:
    image: schickling/beanstalkd:latest
    container_name: health_beanstalksvc
    networks:
      - health-nlp-network   
    ports:
      - "127.0.0.1:11300:11300"
  elasticsvc:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.4.3
    container_name: health_elasticsvc
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks:
      - health-nlp-network   
    volumes:
      - ./esdata:/usr/share/elasticsearch/data
    ports:
      - "127.0.0.1:9200:9200"
  health-nlp:
    build: .
    container_name: health-nlp 
    volumes:
      - .:/usr/src/app
    networks:
      - health-nlp-network
    depends_on:
      - beanstalksvc
      - elasticsvc


networks:
  health-nlp-network:
    external:
      name: health-nlp-network 
