version: '2'
services:
  beanstalkd:
    image: schickling/beanstalkd
    container_name: health_beanstalkd
    ports:
      - "11300:11300"
  health-nlp:
    build: .
    container_name: health-nlp 
    volumes:
      - .:/usr/src/app
    depends_on:
      - beanstalkd